######################################################################
# Automatically generated by qmake (3.0) ? 7? 14 20:42:17 2018
######################################################################

TEMPLATE = subdirs
SUBDIRS = modules gui
TARGET = aerovision3dev

DEPENDPATH += . gui modules
INCLUDEPATH += . gui modules
