######################################################################
# Automatically generated by qmake (3.0) ? 7? 14 20:43:31 2018
######################################################################

TEMPLATE = app
TARGET = gui

QT += opengl
#QT += designer
QT += uitools


LIBS += -L/usr/local/lib -lkqt -lkqtgl -lktl -lGLU

# Input
HEADERS += \
mainwindow.h\
gl.h

SOURCES += main.cpp \
mainwindow.cpp\
gl.cpp\
../modules/arm.cpp 


FORMS += parameter.ui 






